
Keep your eye on the twisted
----------------------------

turn on the tube, what do I see ?
a bunch of hateful people talking to me
the crap they say's been heard before
and that's what started up the 2nd World War

so many people see what's going on
heads should be lifted

keep your eye on the twisted
we've seen it all before
little minds can't be shifted
watch out they are back for more

they call it pride to wave the flag
shaving the hair off their brainless heads
I think the world has seen enough
there is too much talking now it's time to get tough

too many people know what's going down
heads should be lifted

keep your eye on the twisted
we've seen it all before
little minds can't be shifted
watch out they are back for more

hey twisted - what's in your head - so twisted
hey twisted - go clear your mind - you're misled

steps should be taken to stop what they're makin'
heads should be lifted... to see what's going on

they spread their mental disease
ignorance needs a leader to make their mass increase

so keep your eye on the twisted...





Lyrics taken from "Keep your eye on the twisted" by Pink Cream 69

