
The Way of the Tao - The Assembler Programmer
---------------------------------------------

Once an apprentice asked a Master what languages he knew. And the
Master thought a while, and named many. Anf the apprentice said,
"Must I know all those to be a Master ?" And the Master replied, "No,
my son. You need to learn as many as you need to do all the machine can do.
He is a Master who can make the machine do all the machine can do."
So the apprentice asked, "Can this be dne in any language ?" and the
Master replied, "No, only in assembler. But in the other languages
may be done many things. So to be a Master you may know whatever
languages suit your fancy, but you must know assembler, for it is the
language of the Tao." And the apprentice asked, "Of all the languages
you know, whitch do you use ?" And the Master smiled and said,
"Assembler".
"But Master," the apprentice asked, "I`ve heard one say that when
at last thr machine you used to code for became obsolete, he was able
to port his code by compiling it for the new machine, and you had to
translate yours. Is this not a great advantage ?" And the Master smiled
and said," My son, that one has moved to a better machine, and does not
know it. His compiler creates code that pains the eye to see in debug it
is so ugly. But he knows not, for he has never seen it. When I ported
my code, I was given the change to learn a new instruction set, and to
discover all the wonderful things done by the Masters who wrote the bios
and the operating syste. And that one curseth them for the way they hath
allocated the memory, and he doth not know of the miracles they have
performed. Is that the way of the Tao?"
